### ISSUE TITLE
Working great until crashes out with 'exit status 2'

### ISSUE THREAD

**Issue by ixionx** [brutella/hklifx#4]
Hi all, 

Love the project, but I'm having a few issues with it. Everything works great, but the script crashes out as shown below.

"goroutine 1229 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f724c0be0c0, 0x72, 0xc82000e1d0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(_pollDesc).Wait(0xc820407250, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc820407250, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).Read(0xc8204071f0, 0xc820152000, 0x1000, 0x1000, 0x0, 0x7f724c0a7050, 0xc82000e1d0)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(_conn).Read(0xc8203722d0, 0xc820152000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
bufio.(_Reader).fill(0xc8202cdb00)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).Read(0xc8202cdb00, 0xc820505a20, 0x2, 0x8, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f724c0bd0d0, 0xc8202cdb00, 0xc820505a20, 0x2, 0x8, 0x2, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f724c0bd0d0, 0xc8202cdb00, 0xc820505a20, 0x2, 0x8, 0xd, 0x0, 0x0)
    /usr/local/go/src/io/io.go:316 +0x62
encoding/binary.Read(0x7f724c0bd0d0, 0xc8202cdb00, 0x7f724c0ac9f0, 0xbae8c8, 0x7ac600, 0xc820505a10, 0x0, 0x0)
    /usr/local/go/src/encoding/binary/binary.go:148 +0x136
github.com/brutella/hc/crypto.(_secureSession).Decrypt(0xc8201609c0, 0x7f724c0bd0d0, 0xc8202cdb00, 0x0, 0x0, 0x0, 0x0)
    /home/luke/go/src/github.com/brutella/hc/crypto/secure_session.go:98 +0x124
github.com/brutella/hc/netio.(_HAPConnection).DecryptedRead(0xc820528930, 0xc82014b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/luke/go/src/github.com/brutella/hc/netio/connection.go:68 +0x16b
github.com/brutella/hc/netio.(_HAPConnection).Read(0xc820528930, 0xc82014b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/luke/go/src/github.com/brutella/hc/netio/connection.go:100 +0x70
net/http.(_liveSwitchReader).Read(0xc8205876f8, 0xc82014b000, 0x1000, 0x1000, 0xc82048f430, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:219 +0xa4
io.(_LimitedReader).Read(0xc820503b40, 0xc82014b000, 0x1000, 0x1000, 0x200000003, 0x0, 0x0)
    /usr/local/go/src/io/io.go:427 +0xbd
bufio.(_Reader).fill(0xc820551e00)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).ReadSlice(0xc820551e00, 0xc81ffe970a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(_Reader).ReadLine(0xc820551e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:357 +0x53
net/textproto.(_Reader).readLineSlice(0xc820529020, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(_Reader).ReadLine(0xc820529020, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820551e00, 0xc8202d0b60, 0x0, 0x0)
    /usr/local/go/src/net/http/request.go:653 +0xb6
net/http.(_conn).readRequest(0xc8205876b0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:633 +0x32f
net/http.(_conn).serve(0xc8205876b0)
    /usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
exit status 2"

I'm also getting 
[ERR] bonjour: Failed to bind the udp6 port: listen udp6 :5354: bind: address already in use
but the lights with Siri still can be toggled on and off until it crashes out.

Any help would be greatly appreciated. 

I'm seeing the the same issue in UbuntuMATE and Windows 8.

**Comment by timbleck** [comment]
Seeing the same issues on my Raspberry Pi using Raspbian Wheezy. I've setup monit to check the process and restart it after crashing.

**Comment by ixionx** [comment]
I've just installed Monit. 
Would you mind sharing with me what you wrote in your /etc/monit.conf or /etc/monit/monitrc file to add in hklifx? 
Thanks!

**Comment by brutella** [comment]
@ixionx Please paste the full stack trace

**Comment by timbleck** [comment]
@ixionx please find the minified monit configuration below

```
check process hklifx pidfile /tmp/hklifx.pid
  start program = "/bin/su -l -c 'nohup hklifx -pin $PIN -v > /var/log/hklifx.log 2>&1 & echo $! > /tmp/hklifx.pid' $USER"
  stop program = "/bin/kill $(cat /tmp/hklifx.pid)"
```

**Comment by chongkwongsheng** [comment]
I seem to be getting this exit status 2 after a while and I have to repeat the run command on Mac Terminal. This happens almost every 2-3 days.

**Comment by brutella** [comment]
@chongkwongsheng Please update all imported libraries – this should already be fixed

**Comment by chongkwongsheng** [comment]
Sorry, can I confirm how to do this? I've only started downloading and using hklifx this month.

**Comment by brutella** [comment]
Update the master branch from the following projects
- `github.com/brutella/hc`
- `github.com/pdf/golifx`

For example

```
> cd $GOPATH/src/github.com/brutella/hc
> git checkout master
> git pull origin master
```

**Comment by chongkwongsheng** [comment]
Hi Matthias,

I have done so for both and received four up-to-date responses for the branch. I have also reinstalled hklifx and reset my HomeKit. I still crash with "exit status 2".

What information would be useful to troubleshoot and what should I remove for privacy? Thanks.
